#!/usr/bin/env sh
language: C
before_install:
- gcc -o helloAsm hello_asm.o
- echo "before install!"
- chmod +x ./gen_sh.sh
install: ./gen_sh.sh
before_script: chmod +x hello_world_asm
script: ./hello_world_asm
after_success: echo "success!"
after_failure: echo "failure!"
after_script: echo "end!"
