#!/usr/bin/env sh
language: C
sudo: false
os: osx
osx_image: xcode9.0.1
before_install:
- echo "before install!"
- chmod +x ./gen_sh.sh
install: ./gen_sh.sh
before_script: chmod +x hello_world_asm
script: echo "emmmmm"
after_success: echo "success!"
after_failure: echo "failure!"
after_script: echo "end!"

jobs:
  include:
    - stage: Github Release
      script: ./hello_world_asm
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: ./hello_world_asm
        skip_cleanup: true
        on:
          tags: true

